name: Run Python Telegram Bot

on:
  schedule:
    - cron: '0 15 * * *'  # runs every day at 11:00 AM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot
        pip install -r requirements.txt
    - name: Execute Python script
      run: python main.py
