name: Run Python Telegram Bot

on:
  schedule:
    - cron: '0 11 * * *'  # runs every day at 11:00 AM

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install python-telegram-bot  # Add any other dependencies you need
    - name: Execute Python script
      run: python main.py
